import { describe, it, expect } from 'vitest';
import { generatePrComment } from './markdown-report';
import type { ScanSummary, NormalizedViolation } from '@a11y-guard/shared-types';

describe('Markdown Report Generator', () => {
  it('generates a clean passing report with baseline score', () => {
    const summary: ScanSummary = {
      scanId: 'scan-1',
      commitSha: 'abc1234',
      repositoryFullName: 'acme/webapp',
      prNumber: 42,
      score: 95.0,
      baselineScore: 90.0,
      conclusion: 'success',
      scannedPagesCount: 3,
      durationMs: 1200,
      configFound: true,
      diff: {
        newViolations: [],
        existingViolations: [],
        resolvedViolations: [],
        totalCurrentCount: 0,
        totalBaselineCount: 0,
      },
    };

    const markdown = generatePrComment(summary);
    expect(markdown).toContain('## ♿ a11y-guard: PASSED ✅');
    expect(markdown).toContain('Baseline: 90 → Current: 95');
    expect(markdown).toContain('| 📄 Scanned Pages | 3 |');
    expect(markdown).toContain('Report generated by');
  });

  it('generates a failing report with new violations breakdown', () => {
    const violation: NormalizedViolation = {
      id: 'fp-1',
      ruleId: 'color-contrast',
      impact: 'critical',
      description: 'Element has insufficient color contrast',
      helpUrl: 'https://deque.com/rules/color-contrast',
      wcagCriteria: ['wcag143'],
      wcagLevel: 'AA',
      htmlSnippet: '<button class="btn-grey">Click me</button>',
      targetSelector: 'button.btn-grey',
      normalizedSelector: 'button.btn-grey',
      url: 'http://localhost:3000/',
    };

    const summary: ScanSummary = {
      scanId: 'scan-2',
      commitSha: 'def5678',
      repositoryFullName: 'acme/webapp',
      prNumber: 42,
      score: 75.0,
      conclusion: 'failure',
      scannedPagesCount: 1,
      durationMs: 800,
      configFound: true,
      diff: {
        newViolations: [violation],
        existingViolations: [],
        resolvedViolations: [],
        totalCurrentCount: 1,
        totalBaselineCount: 0,
      },
    };

    const markdown = generatePrComment(summary);
    expect(markdown).toContain('## ♿ a11y-guard: FAILED ❌');
    expect(markdown).toContain('🔴 **Critical**');
    expect(markdown).toContain('color-contrast');
    expect(markdown).toContain('button.btn-grey');
  });

  it('truncates comment if character count exceeds limit', () => {
    const newViolations: NormalizedViolation[] = Array(500)
      .fill(null)
      .map((_, i) => ({
        id: `fp-${i}`,
        ruleId: `rule-${i}`,
        impact: 'serious',
        description:
          'Very long repeated description text that consumes character count in markdown comment '.repeat(
            3,
          ),
        wcagCriteria: ['wcag143'],
        htmlSnippet: `<div>Long snippet ${i}</div>`,
        targetSelector: `div.item-${i}`,
        normalizedSelector: `div.item`,
        url: `http://localhost:3000/path-${i}`,
      }));

    const summary: ScanSummary = {
      scanId: 'scan-3',
      commitSha: '999',
      repositoryFullName: 'acme/webapp',
      score: 50.0,
      conclusion: 'failure',
      scannedPagesCount: 10,
      durationMs: 5000,
      configFound: true,
      diff: {
        newViolations,
        existingViolations: [],
        resolvedViolations: [],
        totalCurrentCount: 500,
        totalBaselineCount: 0,
      },
    };

    const markdown = generatePrComment(summary);
    expect(markdown.length).toBeLessThanOrEqual(65500);
    expect(markdown).toContain('Comment truncated due to');
  });
});
