import type { ScanSummary, NormalizedViolation, ImpactSeverity } from '@a11y-guard/shared-types';

const MAX_GITHUB_COMMENT_LENGTH = 65500;

const IMPACT_BADGES: Record<ImpactSeverity, string> = {
  critical: '🔴 **Critical**',
  serious: '🟠 **Serious**',
  moderate: '🟡 **Moderate**',
  minor: '🔵 **Minor**',
};

function formatViolationRow(v: NormalizedViolation): string {
  const badge = IMPACT_BADGES[v.impact] || v.impact;
  const helpLink = v.helpUrl ? `[${v.ruleId}](${v.helpUrl})` : `\`${v.ruleId}\``;
  const snippet = v.htmlSnippet ? `\`\`\`html\n${v.htmlSnippet}\n\`\`\`` : 'N/A';
  const wcag = v.wcagCriteria.length > 0 ? v.wcagCriteria.join(', ') : 'N/A';

  return `
<details>
<summary>${badge}: ${helpLink} on <code>${v.url}</code></summary>

- **Description:** ${v.description}
- **WCAG Criteria:** ${wcag} ${v.wcagLevel ? `(Level ${v.wcagLevel})` : ''}
- **Target Selector:** \`${v.targetSelector}\`

**Code Snippet:**
${snippet}

</details>
`;
}

export function generatePrComment(summary: ScanSummary): string {
  const statusEmoji = summary.conclusion === 'success' ? '✅' : '❌';
  const statusText = summary.conclusion === 'success' ? 'PASSED' : 'FAILED';

  const scoreDiff =
    summary.baselineScore !== undefined
      ? `(Baseline: ${summary.baselineScore} → Current: ${summary.score})`
      : `(Score: ${summary.score}/100)`;

  let markdown = `## ♿ a11y-guard: ${statusText} ${statusEmoji}\n\n`;
  markdown += `**Accessibility Score:** **${summary.score}/100** ${scoreDiff}\n\n`;

  // Summary Table
  markdown += `### 📊 Scan Overview\n\n`;
  markdown += `| Metric | Count |\n`;
  markdown += `| :--- | :--- |\n`;
  markdown += `| 📄 Scanned Pages | ${summary.scannedPagesCount} |\n`;
  markdown += `| 🔴 New Violations | ${summary.diff.newViolations.length} |\n`;
  markdown += `| 🟡 Existing Violations | ${summary.diff.existingViolations.length} |\n`;
  markdown += `| 🎉 Resolved Violations | ${summary.diff.resolvedViolations.length} |\n\n`;

  // New Violations Details
  if (summary.diff.newViolations.length > 0) {
    markdown += `### 🚨 New Violations (${summary.diff.newViolations.length})\n`;
    for (const v of summary.diff.newViolations) {
      const row = formatViolationRow(v);
      if ((markdown + row).length > MAX_GITHUB_COMMENT_LENGTH - 500) {
        markdown += `\n> ⚠️ *Comment truncated due to GitHub size limits. Additional new violations omitted.*\n`;
        break;
      }
      markdown += row;
    }
    markdown += `\n`;
  }

  // Resolved Violations Details
  if (summary.diff.resolvedViolations.length > 0) {
    markdown += `### 🎉 Resolved Violations (${summary.diff.resolvedViolations.length})\n`;
    markdown += `<details><summary>Click to view fixed accessibility issues</summary>\n\n`;
    for (const v of summary.diff.resolvedViolations) {
      markdown += `- ~\`${v.ruleId}\`~ on \`${v.url}\`: ${v.description}\n`;
    }
    markdown += `\n</details>\n\n`;
  }

  // Footer
  markdown += `---\n*Report generated by [a11y-guard](https://github.com/a11y-guard)*`;

  if (markdown.length > MAX_GITHUB_COMMENT_LENGTH) {
    markdown =
      markdown.substring(0, MAX_GITHUB_COMMENT_LENGTH - 100) +
      '\n\n...[Comment truncated due to size limit]';
  }

  return markdown;
}
